# Classificação de Categorias de Notícias

Neste notebook é apresentado o processo de Análise Exploratória dos dados (EDA) e o pré-processamento.

In [1]:
import pandas as pd
import numpy as np
import kagglehub

In [ ]:
# Download dos dados
path = kagglehub.dataset_download("marlesson/news-of-the-site-folhauol")
print("Path to dataset files:", path)

# Análise Exploratória dos Dados

In [4]:
df = pd.read_csv('../data/articles.csv')

In [5]:
print(f"Dimensões do dataset: {df.shape}")
df.head()

Dimensões do dataset: (167053, 6)

,title,text,date,category,subcategory,link
0,"Lula diz que está 'lascado', mas que ainda tem...",Com a possibilidade de uma condenação impedir ...,2017-09-10,poder,NaN,http://www1.folha.uol.com.br/poder/2017/10/192...
1,"'Decidi ser escrava das mulheres que sofrem', ...","Para Oumou Sangaré, cantora e ativista malines...",2017-09-10,ilustrada,NaN,http://www1.folha.uol.com.br/ilustrada/2017/10...
2,Três reportagens da Folha ganham Prêmio Petrob...,Três reportagens da Folha foram vencedoras do ...,2017-09-10,poder,NaN,http://www1.folha.uol.com.br/poder/2017/10/192...
3,Filme 'Star Wars: Os Últimos Jedi' ganha trail...,A Disney divulgou na noite desta segunda-feira...,2017-09-10,ilustrada,NaN,http://www1.folha.uol.com.br/ilustrada/2017/10...
4,CBSS inicia acordos com fintechs e quer 30% do...,"O CBSS, banco da holding Elopar dos sócios Bra...",2017-09-10,mercado,NaN,http://www1.folha.uol.com.br/mercado/2017/10/1...

In [6]:
print("Quantidade de valores ausentes por coluna:")
df.isna().sum()

Quantidade de valores ausentes por coluna:

title               0
text              765
date                0
category            0
subcategory    137418
link                0
dtype: int64

In [7]:
print("Porcentagem de valores ausentes por coluna:")
(df.isna().mean())*100

Porcentagem de valores ausentes por coluna:

title           0.000000
text            0.457938
date            0.000000
category        0.000000
subcategory    82.260121
link            0.000000
dtype: float64

In [9]:
print(f"Quantidade de categorias únicas: {len(df['category'].unique())} \n")
print('Categorias únicas existentes:')
list(df['category'].unique())

Quantidade de categorias únicas: 48

Categorias únicas existentes:

['poder',
 'ilustrada',
 'mercado',
 'mundo',
 'esporte',
 'tec',
 'cotidiano',
 'ambiente',
 'equilibrioesaude',
 'sobretudo',
 'colunas',
 'educacao',
 'tv',
 'banco-de-dados',
 'opiniao',
 'ciencia',
 'paineldoleitor',
 'saopaulo',
 'ilustrissima',
 'seminariosfolha',
 'turismo',
 'empreendedorsocial',
 'serafina',
 'asmais',
 'o-melhor-de-sao-paulo',
 'bbc',
 'comida',
 'musica',
 'folhinha',
 'especial',
 'treinamento',
 'multimidia',
 'cenarios-2017',
 'topofmind',
 'dw',
 'ombudsman',
 'contas-de-casa',
 'mulher',
 '2016',
 'guia-de-livros-discos-filmes',
 'treinamentocienciaesaude',
 'rfi',
 'vice',
 'bichos',
 'euronews',
 'guia-de-livros-filmes-discos',
 'infograficos',
 '2015']

In [10]:
print('Distribuição das categorias:')
df['category'].value_counts()

Distribuição das categorias:

category
poder                           22022
colunas                         21622
mercado                         20970
esporte                         19730
mundo                           17130
cotidiano                       16967
ilustrada                       16345
opiniao                          4525
paineldoleitor                   4011
saopaulo                         3955
tec                              2260
tv                               2142
educacao                         2118
turismo                          1903
ilustrissima                     1411
ciencia                          1335
equilibrioesaude                 1312
sobretudo                        1057
bbc                               980
folhinha                          876
empreendedorsocial                841
comida                            828
asmais                            548
ambiente                          491
seminariosfolha                   379
serafina                          334
o-melhor-de-sao-paulo             189
vice                              146
guia-de-livros-discos-filmes      143
topofmind                          86
banco-de-dados                     64
dw                                 48
especial                           43
cenarios-2017                      43
infograficos                       43
rfi                                29
guia-de-livros-filmes-discos       28
multimidia                         27
treinamento                        21
treinamentocienciaesaude           18
mulher                             16
euronews                            8
ombudsman                           3
contas-de-casa                      2
musica                              1
bichos                              1
2016                                1
2015                                1
Name: count, dtype: int64

# Pré-processamento dos dados

Nesta etapa são removidas colunas que não serão utilizadas pelo modelo.

Foram mantidos apenas:

- título;
- texto;
- categoria.

Embora a coluna "text" contenha algumas notícias sem conteúdo, esses registros não foram descartados. Durante o treinamento, a entrada do modelo foi construída a partir da concatenação dos campos "title" e "text". Dessa forma, mesmo quando a coluna "text" da notícia está vazia, o título fornece informação suficiente para compor a entrada do modelo, evitando a existência de documentos vazios durante o treinamento.

In [11]:
# Removendo as colunas que não serão considerados durante o treinamento 
df_filtered = df.drop(columns=['date', 'subcategory', 'link'])
df_filtered.head()

,title,text,category
0,"Lula diz que está 'lascado', mas que ainda tem...",Com a possibilidade de uma condenação impedir ...,poder
1,"'Decidi ser escrava das mulheres que sofrem', ...","Para Oumou Sangaré, cantora e ativista malines...",ilustrada
2,Três reportagens da Folha ganham Prêmio Petrob...,Três reportagens da Folha foram vencedoras do ...,poder
3,Filme 'Star Wars: Os Últimos Jedi' ganha trail...,A Disney divulgou na noite desta segunda-feira...,ilustrada
4,CBSS inicia acordos com fintechs e quer 30% do...,"O CBSS, banco da holding Elopar dos sócios Bra...",mercado

In [16]:
print("Quantidade de valores ausentes por coluna:")
df_filtered.isna().sum()

Quantidade de valores ausentes por coluna:

title         0
text        760
category      0
dtype: int64

In [12]:
# Remove categorias com poucas amostras para reduzir o impacto de classes extremamente raras durante o treinamento
min_samples = 8
category_counts = df_filtered['category'].value_counts()
categories_to_keep = category_counts[category_counts >= min_samples].index
df_filtered = df_filtered[df_filtered['category'].isin(categories_to_keep)]

In [13]:
# Mostrando Total de categorias e Total de itens no dataset filtrado
print(f"Dimensões do dataset após filtragem: {df_filtered.shape}")
print(f"Total de categorias únicas após filtragem: {df_filtered['category'].nunique()} \n")

# Verificando a distribuição de dados após a filtragem
print(f"Distribuição das categorias depois da filtragem:")
df_filtered['category'].value_counts()

Dimensões do dataset após filtragem: (167044, 3)
Total de categorias únicas após filtragem: 42

Distribuição das categorias depois da filtragem:

category
poder                           22022
colunas                         21622
mercado                         20970
esporte                         19730
mundo                           17130
cotidiano                       16967
ilustrada                       16345
opiniao                          4525
paineldoleitor                   4011
saopaulo                         3955
tec                              2260
tv                               2142
educacao                         2118
turismo                          1903
ilustrissima                     1411
ciencia                          1335
equilibrioesaude                 1312
sobretudo                        1057
bbc                               980
folhinha                          876
empreendedorsocial                841
comida                            828
asmais                            548
ambiente                          491
seminariosfolha                   379
serafina                          334
o-melhor-de-sao-paulo             189
vice                              146
guia-de-livros-discos-filmes      143
topofmind                          86
banco-de-dados                     64
dw                                 48
cenarios-2017                      43
especial                           43
infograficos                       43
rfi                                29
guia-de-livros-filmes-discos       28
multimidia                         27
treinamento                        21
treinamentocienciaesaude           18
mulher                             16
euronews                            8
Name: count, dtype: int64

In [15]:
# Salvando o dataset filtrado
df_filtered.to_csv('../data/filtered_articles.csv', index=False)